name: Sync to Personal Repo

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout organization repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}
          
      - name: Configure Git
        run: |
          git config --global user.name 'Hyeongyu-619'
          git config --global user.email 'your-email@example.com'
          
      - name: Push to personal repository
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          echo "Setting up remote..."
          git remote remove origin || true
          git remote add origin https://${TOKEN}@github.com/Hyeongyu-619/reindeer-letter-fe.git
          echo "Pushing changes..."
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          git push -f origin HEAD:$BRANCH_NAME